; convpng v6.8
; this file contains all the graphics for easier inclusion in a project
#include "MCMENU.asm"
MCMENU_num equ 6

button equ MCMENU + 0
button_offset equ 0
button_width equ 240
button_height equ 22
button_down equ MCMENU + 3
button_down_offset equ 5282
button_down_width equ 240
button_down_height equ 22
mcLogo1 equ MCMENU + 6
mcLogo1_offset equ 10564
mcLogo1_width equ 125
mcLogo1_height equ 45
mcLogo2 equ MCMENU + 9
mcLogo2_offset equ 16191
mcLogo2_width equ 146
mcLogo2_height equ 45
tileRepeat equ MCMENU + 12
tileRepeat_offset equ 22763
tileRepeat_width equ 16
tileRepeat_height equ 16
sizeof_MCMENU_pal equ 252
MCMENU_pal equ MCMENU + 15
MCMENU_pal_offset equ 23021

